version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_CONNECTIONSTRING: ${DATABASE_CONNECTIONSTRING}
      VANTAGE_API_KEY: ${VANTAGE_API_KEY}
